---
# Source: zookeeper-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-operator-deployment
  labels:
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: zookeeper-operator
    app.kubernetes.io/version: "23.11.0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper-operator
      app.kubernetes.io/instance: zookeeper-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper-operator
        app.kubernetes.io/instance: zookeeper-operator
    spec:
      serviceAccountName: zookeeper-operator-serviceaccount
      securityContext:
        {}
      containers:
        - name: zookeeper-operator
          securityContext:
            {}
          image: "docker.stackable.tech/stackable/zookeeper-operator:23.11.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/stackable/zookeeper-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: zookeeper-operator-configmap
