---
# Source: hdfs-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-operator-deployment
  labels:
    helm.sh/chart: hdfs-operator-23.11.0
    app.kubernetes.io/name: hdfs-operator
    app.kubernetes.io/instance: hdfs-operator
    app.kubernetes.io/version: "23.11.0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: hdfs-operator
      app.kubernetes.io/instance: hdfs-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hdfs-operator
        app.kubernetes.io/instance: hdfs-operator
    spec:
      serviceAccountName: hdfs-operator-serviceaccount
      securityContext:
        {}
      containers:
        - name: hdfs-operator
          securityContext:
            {}
          image: "docker.stackable.tech/stackable/hdfs-operator:23.11.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/stackable/hdfs-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: hdfs-operator-configmap
