---
# Source: secret-operator/templates/configmap.yaml
apiVersion: v1
data:
  {}
kind: ConfigMap
metadata:
  name: secret-operator-configmap
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/version: "23.11.0"
---
# Source: secret-operator/templates/csidriver.yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: secrets.stackable.tech
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Ephemeral
    - Persistent
---
# Source: secret-operator/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secret-operator-daemonset
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/version: "23.11.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-operator
      app.kubernetes.io/instance: secret-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
    spec:
      serviceAccountName: secret-operator-serviceaccount
      securityContext:
        {}
      containers:
        - name: secret-operator
          securityContext:
            privileged: true
            runAsUser: 0
          image: "docker.stackable.tech/stackable/secret-operator:23.11.0"
          imagePullPolicy: IfNotPresent
          resources:
            
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PRIVILEGED
              value: "true"
          volumeMounts:
            - name: csi
              mountPath: /csi
            - name: mountpoint
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: tmp
              mountPath: /tmp
        - name: external-provisioner
          image: "docker.stackable.tech/k8s/sig-storage/csi-provisioner:v3.1.0"
          imagePullPolicy: IfNotPresent
          resources:
            
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          args:
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
            - --extra-create-metadata
          volumeMounts:
            - name: csi
              mountPath: /csi
        - name: node-driver-registrar
          image: "docker.stackable.tech/k8s/sig-storage/csi-node-driver-registrar:v2.5.0"
          imagePullPolicy: IfNotPresent
          resources:
            
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/secrets.stackable.tech/csi.sock
          volumeMounts:
            - name: registration-sock
              mountPath: /registration
            - name: csi
              mountPath: /csi
      initContainers:
        # https://github.com/stackabletech/secret-operator/issues/251
        # In https://github.com/stackabletech/secret-operator/pull/231 we introduced a breaking change by shortening the CSI registration path
        # This resulted in the following error "node_register.go:43] file exists in socketPath /registration/secrets.stackable.tech-reg.sock but it's not a socket.: &{name:secrets.stackable.tech-reg.sock size:4096 mode:2147484141 modTime:{wall:984732078ext:63815759330 loc:0xf864a0} sys:{Dev:64769 Ino:43688551 Nlink:2 Mode:16877 Uid:0 Gid:0 X__pad0:0 Rdev:0 Size:4096 Blksize:4096 Blocks:8 Atim:{Sec:1680162505 Nsec:36073186} Mtim:{Sec:1680162530 Nsec:984732078} Ctim:{Sec:1680162530 Nsec:984732078} X__unused:[0 0 0]}}"
        # This init container removes the "old" directory, so that a unix socket with the same path can be created instead
        # TODO: Should be removed in a release after 23.4
        - name: migrate-longer-csi-registration-path
          image: "docker.stackable.tech/stackable/secret-operator:23.11.0"
          imagePullPolicy: IfNotPresent
          resources:
            
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          command:
            - /bin/bash
            - -euo
            - pipefail
            - -x
            - -c
            - |
              ls -la /registration
              echo "Removing old (long) CSI registration path"
              if [ -d "/registration/secrets.stackable.tech-reg.sock" ]; then rmdir /registration/secrets.stackable.tech-reg.sock; fi
              ls -la /registration
          volumeMounts:
            - name: registration-sock
              mountPath: /registration
          securityContext:
            runAsUser: 0
      volumes:
        - name: registration-sock
          hostPath:
            # node-driver-registrar appends a driver-unique filename to this path to avoid conflicts
            # see https://github.com/stackabletech/secret-operator/issues/229 for why this path should not be too long
            path: /var/lib/kubelet/plugins_registry
        - name: csi
          hostPath:
            path: /var/lib/kubelet/plugins/secrets.stackable.tech/
        - name: mountpoint
          hostPath:
            path: /var/lib/kubelet/pods/
        - name: tmp
          emptyDir: {}
---
# Source: secret-operator/templates/deployment.yaml
# Templated Deployment disabled for this operator
---
# Source: secret-operator/templates/roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-operator-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
  - apiGroups:
      - secrets.stackable.tech
    resources:
      - secretclasses
    verbs:
      - get
  - apiGroups:
      - listeners.stackable.tech
    resources:
      - listenerclasses
      - podlisteners
    verbs:
      - get
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - privileged
    resources:
    - securitycontextconstraints
    verbs:
    - use
---
# Source: secret-operator/templates/secretclasses.yaml
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: tls
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: secret-provisioner-tls-ca
          namespace: default
        autoGenerate: true
---
# Source: secret-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-operator-serviceaccount
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/version: "23.11.0"
---
# Source: secret-operator/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: secret-operator-clusterrolebinding
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/version: "23.11.0"
subjects:
  - kind: ServiceAccount
    name: secret-operator-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: secret-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: secret-operator/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: secrets.stackable.tech
provisioner: secrets.stackable.tech
