---
# Source: secret-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-operator-serviceaccount
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/version: "23.11.0"
---
# Source: secret-operator/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: secret-operator-clusterrolebinding
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/version: "23.11.0"
subjects:
  - kind: ServiceAccount
    name: secret-operator-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: secret-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
